language: cpp
sudo: required

services:
  - docker

branches:
  only:
    - master

arch:
  packages:
    - qt5-declarative
  script:
    - travis/run.sh

script:
  - curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash
