language: cpp
sudo: required

branches:
  only:
    - master

arch:
  packages:
    - qt5-declarative
  script:
    - travis/run-tests.sh

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
