language: cpp
sudo: required

branches:
  only:
    - master

arch:
  packages:
    - qt5-declarative
  script:
    - travis/run-tests.sh

script:
  - travis/setup-arch-travis.sh "${TRAVIS_BUILD_DIR}"
