language: cpp
sudo: required

branches:
  only:
    - master

arch:
  packages:
    - qt5-declarative
  script:
    - qmllint $(find . -maxdepth 2 -type f -path '*.qml' | xargs)

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
