language: cpp
dist: bionic

branches:
  only:
    - master

before_install:
  - chmod +x .travis/*.sh

addons:
  apt:
    update: true
    packages:
      - qt5-default
      - qtdeclarative5-dev
      - qtdeclarative5-dev-tools

script:
  - source .travis/script.sh
